version: "3"
services:
  reverseproxy:
    image: akwele/runall
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - user
      - feed
    # proxy info
  user:
    # service info goes here
    image: akwele/c3-user
    volumes:
      - $HOME/.aws:/root/.aws

    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRESS_DB: $POSTGRESS_DATABASE 
      POSTGRESS_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE
      AWS_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"

  feed:
    # service info goes here
    image: akwele/c3-feed
    volumes:
      - $HOME/.aws:/root/.aws

    environment:
      POSTGRESS_USERNAME: $POSTGRESS_USERNAME
      POSTGRESS_PASSWORD: $POSTGRESS_PASSWORD 
      POSTGRESS_DB: $POSTGRESS_DATABASE 
      POSTGRESS_HOST: $POSTGRESS_HOST 
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_MEDIA_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"

  frontend:
    # service info goes here
    image: akwele/c3-frontend
    ports:
      - "8100:80"