version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: akwele/runall
  backend_user:
    build:
      context: ../udacity-c3-user
    image: akwele/c3-user
  backend_feed:
    build:
      context: ../udacity-c3-feed  
    image: akwele/c3-feed
  frontend:
    build:
      context: ../udacity-c3-frontend  
    image: akwele/c3-frontend